### ISSUE TITLE
Critical Bug

### ISSUE THREAD

**Issue by VendorAttestation** [hajimes/mmh3#106]
![image](https://github.com/user-attachments/assets/fdf830df-60fb-40a6-b1c7-222dc004655c)

Half the hash is swapped wtf

**Comment by hajimes** [comment]
Hi,
Not sure what library you're using, but my guess is that it might not be compliant with the original C++ MurmurHash3, so you might want to contact its author. Please see #46 if you're interested in technical details.
Thanks for your report,
