### ISSUE TITLE
Unable to build on mmh

### ISSUE THREAD

**Issue by WrenchKing** [hajimes/mmh3#19]
It looks like a previous issue resurfaced. Downloading through pip, I'm unable to build a wheel. 

![selection_001](https://user-images.githubusercontent.com/16004167/47171154-3f4cd880-d308-11e8-9ca6-d8df05ab312c.png)

**Comment by bkarr** [comment]
I also am unable to build:
$ sudo -H pip install mmh3==2.0
Collecting mmh3==2.0
  Using cached https://files.pythonhosted.org/packages/cb/e0/d9459f9d4b56cc78c85f1c1aca54eb0ed89d4ed703da979e09b24806d434/mmh3-2.0.tar.gz
Building wheels for collected packages: mmh3
  Running setup.py bdist_wheel for mmh3 ... error
  Complete output from command /usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1zQ1D/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-dgyuoI --python-tag pp251:
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  cc -O2 -fPIC -Wimplicit -I/usr/lib/pypy/include -c mmh3module.cpp -o build/temp.linux-x86_64-2.7/mmh3module.o
  cc1plus: warning: command line option ‘-Wimplicit’ is valid for C/ObjC but not for C++
  mmh3module.cpp:9:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'cc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mmh3
  Running setup.py clean for mmh3
Failed to build mmh3
Installing collected packages: mmh3
  Running setup.py install for mmh3 ... error
    Complete output from command /usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1zQ1D/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-I0ZxFz/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    cc -O2 -fPIC -Wimplicit -I/usr/lib/pypy/include -c mmh3module.cpp -o build/temp.linux-x86_64-2.7/mmh3module.o
    cc1plus: warning: command line option ‘-Wimplicit’ is valid for C/ObjC but not for C++
    mmh3module.cpp:9:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1zQ1D/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-I0ZxFz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-t1zQ1D/mmh3/

**Comment by RamatiAriel** [comment]
I also encountered the same issue-
have you managed to install it?

**Comment by hajimes** [comment]
Sorry for your inconvenience.

I believe this kind of issues should have been resolved in version 3.0.0, which provided official wheels. I just forgot to close this issue.

Thanks,
