### ISSUE TITLE
mmh3

### ISSUE THREAD

**Issue by yzssbo** [hajimes/mmh3#25]
I also encountered the problem of mm3. I have been very distressed looking for a solution. The errors I see here are not the same as mine. Can you help me?
——————————————————————————————————————————
  1 warning generated.
  creating build/lib.macosx-10.6-intel-3.6
  /usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include build/temp.macosx-10.6-intel-3.6/mmh3module.o build/temp.macosx-10.6-intel-3.6/MurmurHash3.o -o build/lib.macosx-10.6-intel-3.6/mmh3.cpython-36m-darwin.so
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/clang++' failed with exit status 1

**Comment by Alphadelta14** [comment]
macOS 10.14 removed libstdc++ libraries, so I would set -mmacosx-version-min as the error instructed:
```
export MACOSX_DEPLOYMENT_TARGET=10.9
python setup.py build
```

**Comment by ryanfwy** [comment]
@Alphadelta14 it works fine on macOS 10.15. 👍🏻

```
export MACOSX_DEPLOYMENT_TARGET=10.9
pip3 install mmh3
```

**Comment by hajimes** [comment]
@yzssbo thanks for your bug report, @Alphadelta14 and @ryanfwy I really appreciate your pithy answers to address the issue👍🏻

In the recent version of mmh3, I merged @honnibal's commit to fix this problem and distributed wheels for macOS, so I hope this issue has now been resolved.
