### ISSUE TITLE
return different hash between c++ and python

### ISSUE THREAD

**Issue by yyyshi** [hajimes/mmh3#33]
cpp: (compile with the code https://github.com/hajimes/mmh3/blob/master/MurmurHash3.h)
`uint32_t MurmurHash32(const void* key, size_t len) {`
`   uint32_t hash;`
`   MurmurHash3_x86_32(key, (int)len, 0, &hash);`
`    std::cout << "site= " << key << ", code= " << code << std::endl;`
`    return hash;`
`}`

//  output: (import mmh3)
site= www.taobao.com, code= 4076543410

python:
`import mmh3`
`res = mmh3.hash(domain, signed=False)`
`print 'site= %s, code= %s' % (domain, res)`

// output:
site= www.taobao.com, code= 3707551990

why the same site "www.taobao.com" get 4076543410 in cpp while 3707551990 in python?

**Comment by wbolster** [comment]
your c++ code inserts a newline. your python code does not.

**Comment by wbolster** [comment]
(nevermind, i misread on my phone)

**Comment by masagrator** [comment]
You are putting output to hash, and for some reason print "code" instead of hash? Your code is wrong

**Comment by hajimes** [comment]
In addition to what @masagrator pointed out,
mmh3.hash('www.taobao.com', signed=False) should return 4076543410, not 3707551990.

I'm not sure why you got that result. But possibly you tested this library on a 32-bit architecture machine (like i686 or armv7l). If that's the case, please try the new version (3.1.0) which resolved incompatibilities on these architectures.

**Comment by hajimes** [comment]
I close this issue here, because the question was raised more than a year ago and two months have passed since I answered it. It's all my fault, as my response was too late. Thank you for your valuable question, @yyyshi!
