### ISSUE TITLE
Support for hashing data > 16GB

### ISSUE THREAD

**Issue by arieleizenberg** [hajimes/mmh3#36]
`FORCE_INLINE uint64_t getblock ( const uint64_t * p, int i )` uses a 32-bit integer `i` for size, this fails for hashing huge blocks. Change `to FORCE_INLINE uint64_t getblock ( const uint64_t * p, Py_ssize_t i )`.

Here is the pull request:
https://github.com/hajimes/mmh3/pull/34

**Comment by hajimes** [comment]
Sorry for the delay. Version 3.1.0, which incorporates your commit, is now released. Thank you for your contribution.
