### ISSUE TITLE
mmh3 not building anymore?

### ISSUE THREAD

**Issue by metaswirl** [hajimes/mmh3#7]
mmh3 is not compiling when installing through pip via packet or git.
I want to use it for the Bloom filter implemented here:
http://www.maxburstein.com/blog/creating-a-simple-bloom-filter/

Specs of my system:
gcc: 5.1.0
os: archlinux
pip: 7.0.3
git: 2.4.2
python: 3.4.3 / 2.7.9

Output from pip
```
> sudo pip install mmh3
Collecting mmh3
  Using cached mmh3-2.3.tar.gz
Installing collected packages: mmh3
  Running setup.py install for mmh3
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ia20ohxq/mmh3/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dmuabtur-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build/temp.linux-x86_64-3.4
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -I/usr/include/python3.4m -c mmh3module.cpp -o build/temp.linux-x86_64-3.4/mmh3module.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -I/usr/include/python3.4m -c MurmurHash3.cpp -o build/temp.linux-x86_64-3.4/MurmurHash3.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    MurmurHash3.cpp:34:31: error: expected constructor, destructor, or type conversion before ‘(’ token
     #define FORCE_INLINE attribute((always_inline))
                                   ^
    MurmurHash3.cpp:60:1: note: in expansion of macro ‘FORCE_INLINE’
     FORCE_INLINE uint32_t getblock ( const uint32_t * p, int i )
     ^
    MurmurHash3.cpp:34:31: error: expected constructor, destructor, or type conversion before ‘(’ token
     #define FORCE_INLINE attribute((always_inline))
                                   ^
    MurmurHash3.cpp:65:1: note: in expansion of macro ‘FORCE_INLINE’
     FORCE_INLINE uint64_t getblock ( const uint64_t * p, int i )
     ^
    MurmurHash3.cpp:34:31: error: expected constructor, destructor, or type conversion before ‘(’ token
     #define FORCE_INLINE attribute((always_inline))
                                   ^
    MurmurHash3.cpp:73:1: note: in expansion of macro ‘FORCE_INLINE’
     FORCE_INLINE uint32_t fmix ( uint32_t h )
     ^
    MurmurHash3.cpp:34:31: error: expected constructor, destructor, or type conversion before ‘(’ token
     #define FORCE_INLINE attribute((always_inline))
                                   ^
    MurmurHash3.cpp:86:1: note: in expansion of macro ‘FORCE_INLINE’
     FORCE_INLINE uint64_t fmix ( uint64_t k )
     ^
    MurmurHash3.cpp: In function ‘void MurmurHash3_x86_32(const void*, int, uint32_t, void*)’:
    MurmurHash3.cpp:117:36: error: ‘getblock’ was not declared in this scope
         uint32_t k1 = getblock(blocks,i);
                                        ^
    MurmurHash3.cpp:148:15: error: ‘fmix’ was not declared in this scope
       h1 = fmix(h1);
                   ^
    MurmurHash3.cpp: In function ‘void MurmurHash3_x86_128(const void*, int, uint32_t, void*)’:
    MurmurHash3.cpp:178:40: error: ‘getblock’ was not declared in this scope
         uint32_t k1 = getblock(blocks,i*4+0);
                                            ^
    MurmurHash3.cpp:244:15: error: ‘fmix’ was not declared in this scope
       h1 = fmix(h1);
                   ^
    MurmurHash3.cpp: In function ‘void MurmurHash3_x64_128(const void*, int, uint32_t, void*)’:
    MurmurHash3.cpp:279:40: error: ‘getblock’ was not declared in this scope
         uint64_t k1 = getblock(blocks,i*2+0);
                                            ^
    MurmurHash3.cpp:329:15: error: ‘fmix’ was not declared in this scope
       h1 = fmix(h1);
                   ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ia20ohxq/mmh3/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dmuabtur-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ia20ohxq/mmh3
```

**Comment by hajimes** [comment]
Thanks for reporting! I confirmed the bug on gcc 5.1.0. The reason behind this seems gcc 5 and later require stricter format for declaring attributes.

In the branch `fixinline` I corrected the line of the problem.  Can you check if it works?
`git clone -b fixinline https://github.com/hajimes/mmh3.git && cd mmh3 && python setup.py build`

**Comment by metaswirl** [comment]
Thanks for the prompt response :+1: 

It builds and installs without error:

```
> sudo pip3 install git+https://github.com/hajimes/mmh3.git@fixinline
[...]
Successfully installed mmh3-2.31
```

**Comment by hajimes** [comment]
Sounds good. I'll upload it to PyPI soon.

**Comment by WrenchKing** [comment]
It looks like the problem is happening again. I'm unable to build a wheel for mmh3 from "pip install mmh3".

**Comment by makamkkumar** [comment]
Same here with me too

**Comment by GusSand** [comment]
+1

**Comment by bkarr** [comment]
I have the same problem also:
 $ sudo -H pip install mmh3==2.0
Collecting mmh3==2.0
  Using cached https://files.pythonhosted.org/packages/cb/e0/d9459f9d4b56cc78c85f1c1aca54eb0ed89d4ed703da979e09b24806d434/mmh3-2.0.tar.gz
Building wheels for collected packages: mmh3
  Running setup.py bdist_wheel for mmh3 ... error
  Complete output from command /usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1zQ1D/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-dgyuoI --python-tag pp251:
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  cc -O2 -fPIC -Wimplicit -I/usr/lib/pypy/include -c mmh3module.cpp -o build/temp.linux-x86_64-2.7/mmh3module.o
  cc1plus: warning: command line option ‘-Wimplicit’ is valid for C/ObjC but not for C++
  mmh3module.cpp:9:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'cc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mmh3
  Running setup.py clean for mmh3
Failed to build mmh3
Installing collected packages: mmh3
  Running setup.py install for mmh3 ... error
    Complete output from command /usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1zQ1D/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-I0ZxFz/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    cc -O2 -fPIC -Wimplicit -I/usr/lib/pypy/include -c mmh3module.cpp -o build/temp.linux-x86_64-2.7/mmh3module.o
    cc1plus: warning: command line option ‘-Wimplicit’ is valid for C/ObjC but not for C++
    mmh3module.cpp:9:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1zQ1D/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-I0ZxFz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-t1zQ1D/mmh3/

**Comment by ghanendrapiplani** [comment]
unable to build on ubuntu, same error as @bkarr

**Comment by yassinek3ch** [comment]
**1**
```pc@h4xor:~/Desktop$: sudo apt-get install python3 python-dev python3-dev &&  build-essential libssl-dev libffi-dev && libxml2-dev libxslt1-dev zlib1g-dev && python-pip```
**2**
```sudo pip3 install mmh3==2.5.1```

**done**
