### ISSUE TITLE
Python 3.12 support please

### ISSUE THREAD

**Issue by lolminerxmrig** [hajimes/mmh3#74]
Please provide official packaging for 3.11 AND 3.12.

**Comment by hajimes** [comment]
Hi,
mmh3 already provides wheels for Python 3.11 and 3.12.
Support for Python 3.13 (release candidate) will be available in the next version of mmh3, which is expected to be released in the next few days.

**Comment by hajimes** [comment]
mmh3 5.0.0 is now released, with support for Python 3.8-3.13. If you need wheels (built packages), please download them from https://pypi.org/project/mmh3/#files

Thanks,

**Comment by hajimes** [comment]
Judging from their history, this account seems to be a bot.
