### ISSUE TITLE
Can not compile in windows

### ISSUE THREAD

**Issue by XQDD** [hajimes/mmh3#9]
> 
> C:\Users\10324\Downloads\mmh3-master\mmh3-master>python setup.py build
> running build
> running build_ext
> building 'mmh3' extension
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\10324\AppData\Local\Programs\Python\Python36\include -IC:\Users\10324\AppData\Local\Programs\Python\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpmmh3module.cpp /Fobuild\temp.win-amd64-3.6\Release\mmh3module.obj
> mmh3module.cpp
> c:\users\10324\downloads\mmh3-master\mmh3-master\MurmurHash3.h(16): error C2371: 'uint32_t': redefinition; different basic types
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(23): note: see declaration of 'uint32_t'
> mmh3module.cpp(14): error C2371: 'int32_t': redefinition; different basic types
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(19): note: see declaration of 'int32_t'
> mmh3module.cpp(17): error C2371: 'uint32_t': redefinition; different basic types
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(23): note: see declaration of 'uint32_t'
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
> 

Run at Win10 64 bit

**Comment by hajimes** [comment]
Thanks for your error report. I updated my library to solve the issue. Please tell me again if you still have problems.
